### ISSUE TITLE
Can't use integration through Stitch using API token and URL. Getting "Invalid request - we cannot understand the URL you specified."

### ISSUE THREAD

**Issue by mrdeds** [singer-io/tap-quickbase#15] opened 2018-06-25 16:51 UTC
Through Stitch I want to extract data from Quickbase. Here's the configuration:

<img width="788" alt="captura de pantalla 2018-06-25 a la s 11 47 20" src="https://user-images.githubusercontent.com/9302082/41863940-e676f730-786d-11e8-98f1-2aa03f9bdaff.png">

And when testing the connection I get this:
```2018-06-25 16:45:16,886Z   main - INFO Running tap-quickbase version 1.0.2 and target-stitch version 1.7.4
2018-06-25 16:45:17,007Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-quickbase --config /tmp/tap_discover_config.json --discover
2018-06-25 16:45:17,473Z    tap - INFO API GET https://resuelve.quickbase.com/db/.................., {'act': 'API_GetSchema'}
2018-06-25 16:45:19,150Z    tap - CRITICAL Error response from Quick Base (Code 102): Invalid request - we cannot understand the URL you specified.
2018-06-25 16:45:19,151Z    tap - Traceback (most recent call last):
2018-06-25 16:45:19,151Z    tap -   File "tap-env/bin/tap-quickbase", line 11, in <module>
2018-06-25 16:45:19,151Z    tap -     sys.exit(main())
2018-06-25 16:45:19,152Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 483, in main
2018-06-25 16:45:19,152Z    tap -     raise exc
2018-06-25 16:45:19,152Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 480, in main
2018-06-25 16:45:19,152Z    tap -     main_impl()
2018-06-25 16:45:19,152Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 470, in main_impl
2018-06-25 16:45:19,152Z    tap -     do_discover(conn)
2018-06-25 16:45:19,153Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 215, in do_discover
2018-06-25 16:45:19,153Z    tap -     discover_catalog(conn).dump()
2018-06-25 16:45:19,153Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 141, in discover_catalog
2018-06-25 16:45:19,153Z    tap -     for table in conn.get_tables():
2018-06-25 16:45:19,153Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/qbconn.py", line 82, in get_tables
2018-06-25 16:45:19,153Z    tap -     schema = self.request(params, self.appid)
2018-06-25 16:45:19,154Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/qbconn.py", line 52, in request
2018-06-25 16:45:19,154Z    tap -     raise Exception("Error response from Quick Base (Code {}): {}".format(self.error_code, self.error))
2018-06-25 16:45:19,154Z    tap - Exception: Error response from Quick Base (Code 102): Invalid request - we cannot understand the URL you specified.
2018-06-25 16:45:19,175Z   main - INFO Tap exited abnormally with status 1
2018-06-25 16:45:19,176Z   main - INFO Exit status is: Check failed with code None. Discovery failed with code 1 and error message: "Error response from Quick Base (Code 102): Invalid request - we cannot understand the URL you specified.". Tap failed with code None. Target failed with code None. ```

**Comment by dmosorast** [comment] 2018-06-25 18:11
@mrdeds Thanks for submitting this issue. At first glance, it looks like the API URL is missing the slash at the end. I believe the tap isn't accounting for that right now. Try adding a trailing `/` and see if that fixes it.

**Comment by mrdeds** [comment] 2018-06-25 18:33
no, already tried adding it after "db" (and tried it again now) with same results.

**Comment by dmosorast** [comment] 2018-06-25 21:22
The root cause was old configuration options polluting the config.json and overriding the correct values. Closing this issue.

**Closed by dmosorast** 2018-06-25 21:22 UTC
